/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Parser */

#ifndef _Included_Parser
#define _Included_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Parser
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Parser_parse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
