/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArchiveServlet */

#ifndef _Included_ArchiveServlet
#define _Included_ArchiveServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef ArchiveServlet_serialVersionUID
#define ArchiveServlet_serialVersionUID 1LL
#undef ArchiveServlet_serialVersionUID
#define ArchiveServlet_serialVersionUID 1LL
/*
 * Class:     ArchiveServlet
 * Method:    getArchiveJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArchiveServlet_getArchiveJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
