/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArchiveServlet_Pair */

#ifndef _Included_ArchiveServlet_Pair
#define _Included_ArchiveServlet_Pair
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
