/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArchiveFuncsServlet */

#ifndef _Included_ArchiveFuncsServlet
#define _Included_ArchiveFuncsServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef ArchiveFuncsServlet_serialVersionUID
#define ArchiveFuncsServlet_serialVersionUID 1LL
#undef ArchiveFuncsServlet_serialVersionUID
#define ArchiveFuncsServlet_serialVersionUID 1LL
/*
 * Class:     ArchiveFuncsServlet
 * Method:    getArchiveFuncsJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArchiveFuncsServlet_getArchiveFuncsJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
