/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AssemblyServlet */

#ifndef _Included_AssemblyServlet
#define _Included_AssemblyServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef AssemblyServlet_serialVersionUID
#define AssemblyServlet_serialVersionUID 1LL
#undef AssemblyServlet_serialVersionUID
#define AssemblyServlet_serialVersionUID 1LL
/*
 * Class:     AssemblyServlet
 * Method:    getAssemblyJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AssemblyServlet_getAssemblyJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
