/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AssemblyServlet_Instr */

#ifndef _Included_AssemblyServlet_Instr
#define _Included_AssemblyServlet_Instr
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
