/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FunctionsServlet */

#ifndef _Included_FunctionsServlet
#define _Included_FunctionsServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef FunctionsServlet_serialVersionUID
#define FunctionsServlet_serialVersionUID 1LL
#undef FunctionsServlet_serialVersionUID
#define FunctionsServlet_serialVersionUID 1LL
/*
 * Class:     FunctionsServlet
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FunctionsServlet_parse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
